"""
Paper Summary models.
"""

from typing import Dict, List, Any, Optional
from sqlalchemy import String, Text, ForeignKey, DateTime, Integer
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime

from .base import Base, TimestampMixin


class PaperSummary(Base, TimestampMixin):
    """Paper summary generated by AI."""

    __tablename__ = "paper_summaries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to papers table
    paper_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("papers.id", ondelete="CASCADE"),
        nullable=False
    )
    arxiv_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)

    # Summary content
    summary_text: Mapped[str] = mapped_column(Text, nullable=False)
    summary_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="comprehensive, abstract_only, fallback"
    )

    # Extracted figures and images
    figures: Mapped[List[Dict[str, Any]]] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment="List of extracted figures with base64 data"
    )

    # Generation metadata
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow
    )
    generation_model: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="Model used for generation"
    )
    processing_time_ms: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Time taken to generate summary"
    )

    # Quality metrics
    word_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    figure_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    has_full_text: Mapped[bool] = mapped_column(default=False, nullable=False)

    # Relationships
    paper = relationship("Paper", back_populates="summaries")

    def __repr__(self) -> str:
        return f"<PaperSummary(arxiv_id='{self.arxiv_id}', type='{self.summary_type}')>"


class SummaryFeedback(Base, TimestampMixin):
    """User feedback on summary quality."""

    __tablename__ = "summary_feedback"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    summary_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("paper_summaries.id", ondelete="CASCADE"),
        nullable=False
    )

    # Feedback data
    rating: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="1-5 star rating"
    )
    feedback_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Specific feedback categories
    accuracy_rating: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    clarity_rating: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    completeness_rating: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # User info (optional)
    user_agent: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    ip_hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Relationships
    summary = relationship("PaperSummary")

    def __repr__(self) -> str:
        return f"<SummaryFeedback(summary_id={self.summary_id}, rating={self.rating})>"